### ISSUE TITLE
Websockets and Cloudflare

### ISSUE THREAD

**Issue by dparlevliet** [dparlevliet/node.bittrex.api#1]
As per [issue #67](https://github.com/n0mad01/node.bittrex.api/issues/67#issuecomment-328290650)

**Comment by wodphoenix** [comment]
I have the same problem

**Comment by dparlevliet** [comment]
Can you elaborate?

**Comment by mhuggins** [comment]
@dparlevliet It looks like your fix may have broken the ability to override the ability to return true/false from a custom `reconnecting` service handler.

**Comment by dparlevliet** [comment]
It shouldn't. I did add a forced reconnection to the disconnected method so if you want to completely handle reconnection yourself you'd have to override that one, too. Can you share some more information as to what you're doing and how you're doing it?

**Comment by dparlevliet** [comment]
@mhuggins I confirmed that you can indeed replace service handlers as intended. Check the ``examples/bittrex.websockets.client.js`` file for an example on how to do it with the new changes. There are further examples in that folder and here https://github.com/dparlevliet/node.bittrex.api#websockets. If you still have issues please give me some more information on your specific usage.
