### ISSUE TITLE
Websocket takes ages to load?

### ISSUE THREAD

**Issue by springjben** [dparlevliet/node.bittrex.api#100]
When I use the web sockets it takes AGES to load. 

Something as simple as the example:

`bittrex.websockets.client(function() {
  console.log('Websocket connected');
  bittrex.websockets.subscribe(['BTC-ETH'], function(data) {
    if (data.M === 'updateExchangeState') {
      data.A.forEach(function(data_for) {
        console.log('Market Update for '+ data_for.MarketName, data_for);
      });
    }
  });
});`

When the page loads it takes more than 5 seconds to load.

**Comment by springjben** [comment]
Sometimes nothing even popups up.

**Comment by springjben** [comment]
On seconds thoughts, is there a way to just LISTEN to 1 coins price? The 
`bittrex.websockets.listen(function(data, client) {`

Takes ages too but also has to go through all the other bittrex data.

**Comment by springjben** [comment]
Infact if I can just listen to 1 coin it will speed it up dramatically:

`bittrex.websockets.listen(function(data, client) {
      io.emit('setStats', {value: 'Connected', id:'#socket-status'})
      if (data.M === 'updateSummaryState') {
        data.A.forEach(function(data_for) {
          data_for.Deltas.forEach(function(marketsDelta) {
            if (marketsDelta.MarketName == "BTC-"+url) {
              console.log(marketsDelta.Ask)
            }
          })
        })
      }
    })`

How do I make it just listen (get one) coins info.

**Comment by dparlevliet** [comment]
no, you can't listen to just one particular market unfortunately. Not yet, anyway. No idea if they plan to add it.

**Comment by springjben** [comment]
Is there any way to speed up the time it takes for it to listen?

**Comment by aloysius-pgast** [comment]
It does not take that much time

**Comment by springjben** [comment]
If you try and get bittrex Symbol J, it takes ages (and sometimes never loads). Sometimes I feel like there is an error but nothing ever shows.
