### ISSUE TITLE
Can I have these explained properly?

### ISSUE THREAD

**Issue by springjben** [dparlevliet/node.bittrex.api#101]
TimeInEffect: 'IMMEDIATE_OR_CANCEL', // supported options are 'IMMEDIATE_OR_CANCEL', 'GOOD_TIL_CANCELLED', 'FILL_OR_KILL'
 
ConditionType: 'NONE', // supported options are 'NONE', 'GREATER_THAN', 'LESS_THAN'

-----------------------------------------------------------------------------------------------

**IMMEDIATE_OR_CANCEL** - So if there isn't an order where your price and the amount you want is available it just cancels it.

**GOOD_TIL_CANCELLED** - Keeps trying to sell until its sold

**FILL_OR_KILL** - ? Whats the difference between this and IMMEDIATE_OR_CANCEL?

What are the condition types? Does this affect the timeineffect?

Sorry for all the questions lately, is there a donation address for the developers?

**Comment by springjben** [comment]
Also What do these mean?
       O: 0.0005401,
       H: 0.0005401,
       L: 0.00054,
       C: 0.00054002,
       V: 683.10157197,
       T: '2017-12-04T00:40:00',
       BV: 0.36889747 },

Overall?, High, Low, C?, V?, T?, BV?

**Comment by karimhossenbux** [comment]
Open, High, Low, Close, Volume, Time, BaseVolume

**Comment by springjben** [comment]
Brilliant thanks! What about:

IMMEDIATE_OR_CANCEL - So if there isn't an order where your price and the amount you want is available it just cancels it.

GOOD_TIL_CANCELLED - Keeps trying to sell until its sold

FILL_OR_KILL - ? Whats the difference between this and IMMEDIATE_OR_CANCEL?

**Comment by dparlevliet** [comment]
https://en.wikipedia.org/wiki/Fill_or_kill

**Comment by springjben** [comment]
Whats the difference between IMMEDIATE_OR_CANCEL and FILL_OR_KILL ?
