### ISSUE TITLE
Does getorderbook() come with an initial nounce?

### ISSUE THREAD

**Issue by sehlceris** [dparlevliet/node.bittrex.api#103]
I believe that I'm supposed to get the order book via REST, and then keep it updated via websocket, applying changes in the order specified by 'nounce'.

On another exchange's API, the initial order book REST call includes the nonce, to ensure that you didn't miss anything in between the time you make the REST call and subscribe to the websocket.

Is that unnecessary with the Bittrex API? Should I just run the REST call and subscribe to the websocket at the same time, and hope for the best?

Thanks for the help.

**Comment by dparlevliet** [comment]
This library takes care of Nonce handling for you. You can just make requests

**Comment by kamiltrebunia** [comment]
I don't think it answers the question. Without nounce on orderbook there is no way to know if maybe we didn't missed some update. Or am I missing something?

Simple use case: I want to maintain full orderbook on my end. I don't think it's possible with a current API.
