### ISSUE TITLE
What is depth?

### ISSUE THREAD

**Issue by Fuzzyma** [dparlevliet/node.bittrex.api#113]
In your readme you have this command:

```js
bittrex.getorderbook({ market : 'BTC-LTC', depth : 10, type : 'both' }, function( data, err ) {
  console.log( data );
});
```

I was wondering what the depth param is about. I cant find anything about that in the api documentation and adding a depth to the query string does nothing with the result (at least what I saw):
https://bittrex.com/api/v1.1/public/getorderbook?market=BTC-LTC&type=both&depth=10

**Comment by dparlevliet** [comment]
Yes, it appears this param has been removed. I will remove it from the manual
