### ISSUE TITLE
Can't get the market summary. An example doesn't work for me.

### ISSUE THREAD

**Issue by ProgrammingLife** [dparlevliet/node.bittrex.api#114]
I'm trying to run this example code:
```
const bittrex = require('node.bittrex.api');

console.log('Connecting ....');
bittrex.websockets.listen(function(data, client) {
  console.log( data );
  if (data.M === 'updateSummaryState') {
    data.A.forEach(function(data_for) {
      data_for.Deltas.forEach(function(marketsDelta) {
        console.log('Ticker Update for '+ marketsDelta.MarketName, marketsDelta);
      });
    });
  }
});
```

But the output is:
```
$ node marketSummary.js
Connecting ....
Connected!
{ unhandled_data: {} }
{ unhandled_data: {} }
{ unhandled_data: {} }
{ unhandled_data: {} }
^C
```
What's wrong?

**Comment by samholmes** [comment]
I'm now experiencing this issue also. My code used to work, now it's not. I'm investigating the changes I made that broke it. Any ideas from anyone?

**Comment by dparlevliet** [comment]
I cannot replicate this issue. 

However, I have updated the example files with the new recommended usage. Please try that?

**Comment by samholmes** [comment]
The problem is when you override the serviceHandlers.connected function without subscribing to certain channels. The default connected service handler looks like this: https://github.com/dparlevliet/node.bittrex.api/blob/master/node.bittrex.api.js#L237
