### ISSUE TITLE
calling `websockets.subscribe` multiple times only subscribes to the last 

### ISSUE THREAD

**Issue by Fuzzyma** [dparlevliet/node.bittrex.api#115]
Using subscribe multple times does not work. It only subscribes to the last markets used in the last subscribe function.
Furthermore it is not possible to subscribe to anything ever when the connected callback of SignalR was already executed.

**Comment by kevflynn** [comment]
subscribe takes an array param of tickers, so it makes sense that you wouldn't call it multiple times. Instead, call it once with all of the tickers you want to listen to passed as an array param.

**Comment by Fuzzyma** [comment]
My point remains. You should state in your docs that subscibe should never be called more than once.
Beside that the method name implies that you can suvscribe and unsubscribe to any ticker whenever you want. It took me quite some time to dig into your code and see that its just not possible to do what I want.

Instead I replaces the whole lib with my own which is able to do all this with simple node methods (`on and emit`). Much cleaner now
