### ISSUE TITLE
 Maximum call stack size exceeded at getnonce

### ISSUE THREAD

**Issue by prateekjjw001** [dparlevliet/node.bittrex.api#117]
`bittrex.sendCustomRequest( 'https://bittrex.com/api/v1.1/public/buylimit?market=usdt-eth&quantity=0.01&rate=550', function( data ) {
      console.log( data );
      }, true);`

I wrote this simple piece of code and get this error. I have initialised bittrex.options with my key and secret key.  
![image](https://user-images.githubusercontent.com/14296832/34454295-845003c2-ed8e-11e7-9901-77fa858c55d6.png)

**Comment by josepgomes** [comment]
Same here!
