### ISSUE TITLE
bittrex.getorderhistory returning only 200 records

### ISSUE THREAD

**Issue by nengine** [dparlevliet/node.bittrex.api#118]
I am getting order history but it is returning only 200 records.  Is there any parameters can be use for page numbers? Thanks.

```js
function getorderhistory() {		
	bittrex.options({
		'apikey' : config.bitrx.apikey,
		'apisecret' : config.bitrx.secret,
                'baseUrlv2' : 'https://bittrex.com/Api/v2.0'
	});

	bittrex.getorderhistory( {}, function( data, err ) {
		data.result.forEach(order => {
                      console.log(JSON.stringify(order));
                });
	});
}
```

**Comment by dparlevliet** [comment]
Nope, unfortunately not. I also don't think it returns specifically 200 - it actually returns up to 200 of a certain time frame. You can manually download your entire order history from the website and import it and then poll it from then on, but you have to store your own order history if you want more than they provide. The entire history download is protected with a captcha and not available via the API.

**Comment by nengine** [comment]
Ok no problem. Thanks.
