### ISSUE TITLE
updateExchangeState gets buys/sells/fills - what about bid and ask?

### ISSUE THREAD

**Issue by Fuzzyma** [dparlevliet/node.bittrex.api#122]
Hey! Thx for your libraray.
I am a bit confused about the data I get from `updateExchangeState `.
Every object has buys/sells/fills which (at least for me) correspond to trades and not to an orderbook entry.
Are you sure these buys and sells are orders and not trades?
I would expect bids and asks instead when dealing with offers

**Comment by txssseal** [comment]
:+1: this super important to understand.  As far as I can tell the data might be garbage :cry:

**Comment by m4ff** [comment]
This should help you understand. It's from another library, but the underlying protocol is the same. https://github.com/gliwka/bittrex-market/issues/9

**Comment by Fuzzyma** [comment]
No that does not answer my question. I know how to handle the updates (adding, removing, updating). What I was asking is, why it is called `buys/sells and fills`. Especially I am wondering what the `fills` are for? What do they represent?

**Comment by m4ff** [comment]
The developers chose to call the orders `Buys` and `Sells` instead of bids and asks, but they are the same thing in this case. The `Fills` array contains the trades.

**Comment by Fuzzyma** [comment]
aight! Thanks!
