### ISSUE TITLE
How to force reconnect the subscribed client? It stops sometimes from getting the deltas.

### ISSUE THREAD

**Issue by ProgrammingLife** [dparlevliet/node.bittrex.api#123]
I subscribe to summary deltas via: 
`wsclient.call( "CoreHub", "SubscribeToSummaryDeltas" )`
in about 30 minutes of successfully getting the deltas it stops and never get to me deltas anymore. So I should unsubscribe and subscribe to deltas again. How do I do this?

**Comment by usmankhanic** [comment]
Same here - any fix most welcome

**Comment by ProgrammingLife** [comment]
I tried to do something like that for manually reconnect:

```
bittrexClient.end();
connectBittrex(); // bittrex.websockets.client( .... );
```

but it doesn't work for me because the app just exists without continuation.

```
1514884343: Got tickers...
1514884348: Got tickers...
ERROR: connectionLost
ERROR: reconnecting
ERROR: disconnected
Reconnected!
ERROR: connectionLost
ERROR: reconnecting
ERROR: disconnected
Reconnected!
ERROR: connectionLost
ERROR: reconnecting
ERROR: disconnected
Reconnected!
```
it said "reconnected!" but it doesn't get tickers anymore

**Comment by dparlevliet** [comment]
do you have your subscriptions firing onConnect? once it reconnects it will fire the ``onConnect`` method and will start listening again.

**Comment by dparlevliet** [comment]
I have added a watchdog function to help ensure that reconnects happen - i have also updated the README and example files to show the recommended usage.
