### ISSUE TITLE
How can I receive my orders placed via websocket?

### ISSUE THREAD

**Issue by magicdude4eva** [dparlevliet/node.bittrex.api#126]
Hi there,

I have managed to do this on Binance and Bitfenix, but I can not find any information if this is yet supported. Does the current `messageReceived` return this data already and if so, could someone share the payload?

**Comment by dparlevliet** [comment]
You can't auth via websockets yet so you can't receive messages. People have found work arounds by stealing the headers from your browser and adding them as headers in the library, but it's not supported or recommended. Feel free to search the closed issues to find it.
