### ISSUE TITLE
Subscribing to every market with websocket

### ISSUE THREAD

**Issue by char2** [dparlevliet/node.bittrex.api#134]
My understanding is that in order to track the latest price movements of all markets I will need to subscribe to each market via websocket - is this correct and if so, do you know if I will run in to bittrex limits doing this?

Sorry if this is already answered or explained elsewhere, I couldn’t find what I was looking for in my searches.

**Comment by dparlevliet** [comment]
I do this with my own data bot and have never had an issue. You should be fine!
