### ISSUE TITLE
Understanding Tick Values

### ISSUE THREAD

**Issue by bernatfortet** [dparlevliet/node.bittrex.api#14]
When I request tick data, one of the values that `bittrex.websockets.listen` returns is:
```cson
[...]
market: 
  ...
  Volume: 47443.44238722,
  BaseVolume: 3351.7937059,
  ...
[...]
```
I don't really understand these 2 values. They don't change much overtime.

I'm trying to parse this tick data into OHLCV data.
The OHLC part I got it covered,
but the Volume part is still a mistery to me. 
I'm not sure how to calculate the total volume traded for in a given minute based on the Volume and BaseVolume values provided.

Thanks

**Comment by dparlevliet** [comment]
Using BTC-ETH as the example; ``Volume`` is the currency volume (eg, amount of ETH coins) and the ``BaseVolume`` is the volume in the pair value (eg, ETH value in BTC). I believe it's the amount traded in the past 24hrs.

Also see here, https://bitcoin.stackexchange.com/questions/57512/what-is-the-volume-and-basevolume-reported-from-bittrex-api

**Comment by bernatfortet** [comment]
Got it. 
So it sounds like it's not possible to get the volume traded in the last minute or tick. 
I guess I'll have to get that data by polling candles data every minute.

**Comment by dparlevliet** [comment]
You should be able to achieve it if you do your comparison at the start of each minute. Your bot wont be caught up until it's been on for 2 minutes but I wouldn't imagine that to be an issue.

``
var lastValue = false;
var currentSecond = (new Date()).getSeconds();
if (currentSecond == 1) {
  var recentVolume = 0;
  var recentBaseVolume = 0;
  if (lastValue !== false) {
    recentVolume = tickData.Volume - lastValue.Volume;
    recentBaseVolume = tickData.BaseVolume - lastValue.BaseVolume;
  }
  lastValue = tickData;
}
``

**Comment by bernatfortet** [comment]
oh! Of course. That makes sense. Thanks man!
