### ISSUE TITLE
How to subscribe to order's book update?

### ISSUE THREAD

**Issue by ProgrammingLife** [dparlevliet/node.bittrex.api#142]
I can do single **bittrex.getorderbook()** query only. Is it possible to get only changes from the last query? Only new changed items.

**Comment by aloysius-pgast** [comment]
If you want only orderbook changes, it would be better to use ws subscriptions.

**Comment by ProgrammingLife** [comment]
**aloysius-pgast**
Looks like that's what I need. But how to achieve it? :)

**Comment by aloysius-pgast** [comment]
You can check https://github.com/dparlevliet/node.bittrex.api/blob/master/examples/bittrex.websockets.subscribe.example.js

**Comment by ProgrammingLife** [comment]
**aloysius-pgast**
Yes, I tried that example. But looks like it shows only updateExchangeState which states for transactions history only and not for current changes of walls.
