### ISSUE TITLE
Can't make call to Signalr, 503

### ISSUE THREAD

**Issue by ca1987** [dparlevliet/node.bittrex.api#143]
We are using C# HubConnection class and it does not allow us to make a call to <wss://socket.bittrex.com/signalr>

I tried connecting to there server and received following error:

InnerException = {"StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:\r\n{\r\n Transfer-Encoding: chunked\r\n Connection: close\r\n X-Frame-Options: SAMEORIGIN\r\n Expect-CT: max-age=604800, r...

I am relaying this for my programmer.

Could this be the same as https://github.com/n0mad01/node.bittrex.api/issues/67#issuecomment-343736593 ? Due to cloudflare, with a simple fix of connecting using cfscraper?

**Comment by dparlevliet** [comment]
Correct. You will need to compensate for Cloudflare.
