### ISSUE TITLE
Best way to check if an order has been completed?

### ISSUE THREAD

**Issue by springjben** [dparlevliet/node.bittrex.api#146]
Currently I am just creating a setInterval (looping) every second that calls getOpenOrders, if the order has been fulfilled it will tell the user. It loops for 50 seconds, if nothing happens it just cancels the order.

There MUST be a better way of doing this!

**Comment by dparlevliet** [comment]
There isn't, yet, unfortunately. The WebSockets api doesn't allow authentication so we cannot get pushed that information so we must poll it. It's not ideal but hopefully that will change.
