### ISSUE TITLE
is web sockets having troubles last few days?

### ISSUE THREAD

**Issue by denigada** [dparlevliet/node.bittrex.api#156]
My apps connect to web sockets after like 30 minutes. They started usually not working. Is everyone having the same issue?

**Comment by aloysius-pgast** [comment]
Take a look at https://github.com/dparlevliet/node.bittrex.api/issues/153#comment-373899585 (comment). Adding extra headers to CloudScraper helped improve connection delay on my side.

**Comment by denigada** [comment]
@aloysius-pgast Oh I did not notice that post thank you. I looked in the code but couldnt understand adding the headers. I am not that experienced. Is there any chance you can break it down a little bit?

**Comment by alexus2005** [comment]
Why is this closed? This is still an issue and there is no way to pass headers via options.

**Comment by alexus2005** [comment]
That's not a fix - that's a hack. What happens when a new version is out... it should be a parameter of some sort that we were able to pass.
