### ISSUE TITLE
Why there's always a { unhandled_data: { R: true, I: '1' } } data after websocket connected?

### ISSUE THREAD

**Issue by cbwang2016** [dparlevliet/node.bittrex.api#19]

**Comment by TheRealest** [comment]
I believe this is the response to the call to `SubscribeToExchangeDeltas` (see here: https://github.com/dparlevliet/node.bittrex.api/blob/master/node.bittrex.api.js#L229) -- the `R: true` means the response from the server was `true`, so you were successfully subscribed, and the `I: '1'` is the index of the request when it was received, so you can know which request this is the response for in case they are handled out of order.

If you try passing multiple market names to the `.subscribe` call you will see that you receive one of these for each.
