### ISSUE TITLE
Any ways to get fresh data every given period?

### ISSUE THREAD

**Issue by FabioEnne** [dparlevliet/node.bittrex.api#21]
I'm trying to get fresh data of all the markets (highest, lowest, actual) but at every given period, is there any way to achieve this? By using websocket or api calls? Thanks a lot.
I've tryeid something like this:

```
setInterval(function(){
	console.log("---");
	bittrex.websockets.listen( function( data ) {
		  if (data.M === 'updateSummaryState') {
			data.A.forEach(function(data_for) {
			  data_for.Deltas.forEach(function(marketsDelta) {
				console.log('Ticker Update for '+ marketsDelta.MarketName, marketsDelta);
			  });
			});
		  }
		});
},300000);

but once is triggered it keeps on dumping data, I need latest fresh data but only every 5 minutes..
```

**Comment by dparlevliet** [comment]
There is no candle data available via the websockets. You would have to use the raw data the websocket provides and then aggregate that data yourself. For more information on that please see this discussion https://github.com/n0mad01/node.bittrex.api/issues/61

**Comment by FabioEnne** [comment]
Is there a way to disconnect from the socket? I mean my intention was just to connect, get fresh datas, disconnect...after Xmin reconnect, dump datas and so on...any Idea?

**Comment by dparlevliet** [comment]
```javascript
var wsclient;
bittrex.websockets.client(function(client) {
  wsclient = client;
});

setInterval(function() {
  wsclient.end();
}, 5*601000);
```

**Comment by FabioEnne** [comment]
It says cannot read edn of undefined..

**Comment by dparlevliet** [comment]
I use that same system in my own bot so I can't tell you why you're getting that - you'll have to investigate it on your side. Make sure your code matches the style that I provided in the example as the websocket code has changed in this newest version.

**Comment by diestrin** [comment]
I recommend you to take a look at RXjs, it's supper helpful for me to handle the socket and do operations on it.

Here's how it looks like in my code
```ts
const socket$ = Observable
  .fromEventPattern(handler =>
    bittrex.websockets.client(() =>
      bittrex.websockets.subscribe([market], handler)));

const marketUpdates$ = socket$
  .filter(data => data.M === 'updateSummaryState')
  .concatMap(data => Observable.from(data.A))
  .concatMap(deltaFor => Observable.from(deltaFor.Deltas))
  .filter(delta => delta.MarketName === market)
  .do(marketUpdate);

const real$ = marketUpdates$
  .map(mineData)
  .distinctUntilChanged((prev, next) => prev.id === next.id);
```

I have tons of these all over my code

**Comment by khuezy** [comment]
@diestrin that's really awesome.
Can you provide a little more examples?

**Comment by diestrin** [comment]
@khuezy what are you looking for?

**Comment by khuezy** [comment]
Some examples or resources on using the Observables w/ the websockets. From your example, I'm not sure where the Observable gets executed at.

Is it at `.do(marketUpdate`?

what do the handlers `marketUpdate` and `mineData` do?

Sorry, i'm a noob w/ Obs.

Thanks!

**Comment by diestrin** [comment]
Here's a reference to the docs: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

The `.do` is just to run some code i the middle of the observable, like to *do* something.

I like to create different branches with obs so I can hook on any of them, that's why I have them split into multiple variables.

My `mineData` function is just a function to transform the data in the way that I like. Right now I just have
```
function mineData(operation) {
  return {
    id: new Date(operation.TimeStamp).getTime(),
    bid: operation.Bid,
    ask: operation.Ask
  };
}
```

And I subscribe to the obs later in another file to do something with it.
