### ISSUE TITLE
Making bittrex websocket api work in python

### ISSUE THREAD

**Issue by hippylover** [dparlevliet/node.bittrex.api#24]
Hello. Sorry if this is out of place. I tried emailing n0mad01 and he suggested i ask here. I am trying to get the websocket api working in python as that is the language i'm working with. Mostly, i want to get a live orderbook feed working. I am using 'signalr-client'(https://pypi.python.org/pypi/signalr-client/0.0.7). I have looked at the bittrex docx but i can't get it working.

```
from requests import Session
from signalr import Connection
import time

markets = ['BTC-DGB', 'BTC-STRAT']

with Session() as session:
	connection = Connection('http://socket.bittrex.com/signalr', session)

	corehub = connection.register_hub('coreHub')
	connection.start()

	#create new chat message handler
	def print_received_message(data):
		print(data)
		# if data['Nounce'] is not None:
		# 	print('Nounce', data['Nounce'])

		# if data['Deltas'] is not None:
		# 	for value in data['Deltas']:
		# 		print(value)

	#create error handler
	def print_error(error):
		print('error: ', error)

	# debug information, show all data
	def print_raw_data(*args, **kwargs):
		print (args, kwargs)

	connection.received += print_raw_data

	with connection:
		corehub.server.invoke('SubscribeToExchangeDeltas', ['BTC-ETH'])

	corehub.client.on('updateSummaryState', print_received_message)

	connection.error += print_error

	connection.wait(1)
 
while True:
	pass
```

**Comment by dparlevliet** [comment]
Normally I'd say this it off topic but you're in luck because python is my favourite language. Anyway, there were a few issues with the code you provided, not all of them are your fault but rather a fault with the documentation for the python signalR client. I had to dig in to the signalR code to figure out why your code wasn't working. Anyway, I got it working, here's the code.


```python
from requests import Session
from signalr import Connection
import time

markets = ['BTC-DGB', 'BTC-STRAT']

with Session() as session:
	connection = Connection('http://socket.bittrex.com/signalr', session)

	corehub = connection.register_hub('coreHub')

	#create error handler
	def print_error(error):
		print('error: ', error)

	# debug information, show all data
	def print_raw_data(*args, **kwargs):
		print (args, kwargs)

	def ticker_data(*args, **kwargs):
		print "ticker", (args, kwargs)

	def market_data(*args, **kwargs):
		print "market", (args, kwargs)

	#connection.received += print_raw_data
	connection.error += print_error

	connection.start()
	print "sending subscription request"
	for market in markets:
		corehub.server.invoke('SubscribeToExchangeDeltas', market)

	#corehub.client.on('updateSummaryState', ticker_data)
	corehub.client.on('updateExchangeState', market_data)

	connection.wait(120000) # close the connection if no message is received after this many seconds
```

**Comment by dparlevliet** [comment]
The guys https://github.com/ericsomdahl/python-bittrex here might want to know about this so feel free to introduce it to them if they don't already support it

**Comment by hippylover** [comment]
Great stuff! Thanks a bunch! I am wondering why i don't have to do the cloudflare stuff though? Oh, and i suppose sometimes some messages gets skipped(?). I suppose if that happens i have to query for the orderbook and fix it like that.

**Comment by dparlevliet** [comment]
Bittrex has turned cloudflare off at the moment, that's why. I don't know what you mean about messages getting skipped but if it doesn't come to you via the websocket then the issue is at their end.

**Comment by hippylover** [comment]
Ah, ok. So if it's reenabled then i have to use the cloudflare lib. Thge "messages getting skipped" were just something i read here on issue tracker but i haven't experienced it myself. Anyway, if it happens or not i can fix it. Thanks!

**Comment by dparlevliet** [comment]
Yeah, if they turn cloudflare on you'll need to use cloudscraper. No problem, enjoy!

**Comment by hippylover** [comment]
Do you know how i would put the data in an array/dict and not miss any data while doing other things in the script? I haven't really done any async programming(have been trying to avoid it). I don't know if there's a way to tell the computer that the ```corehub.client.on('updateExchangeState', do_stuff)``` line and corresponding function should always be respected, no matter what else im doing in the script at the time.

Is there an easy solution here, or do i have to learn async(asyncio lib?) programming?

**Comment by dparlevliet** [comment]
```python
from requests import Session
from signalr import Connection
import time

markets = ['BTC-DGB', 'BTC-STRAT']
market_buffer = []

with Session() as session:
	connection = Connection('http://socket.bittrex.com/signalr', session)

	corehub = connection.register_hub('coreHub')

	#create error handler
	def print_error(error):
		print('error: ', error)

	# debug information, show all data
	def print_raw_data(*args, **kwargs):
		print (args, kwargs)

	def ticker_data(*args, **kwargs):
		print "ticker", (args, kwargs)

	def market_data(*args, **kwargs):
		market_buffer.append(args)
		print "buffer size", len(market_buffer)

	#connection.received += print_raw_data
	connection.error += print_error

	connection.start()
	print "sending subscription request"
	for market in markets:
		corehub.server.invoke('SubscribeToExchangeDeltas', market)

	#corehub.client.on('updateSummaryState', ticker_data)
	corehub.client.on('updateExchangeState', market_data)

	connection.wait(120000) # close the connection if no message is received after this many seconds
```

**Comment by dparlevliet** [comment]
wait, are you asking how to process that data without affecting your bot or how to store it?

**Comment by hippylover** [comment]
Yeah. I learned some asyncio yesterday. Still haven't gone through the whole tutorial but it seems that if i want to have both the signalr code and the bot code in one script i have to await on everything and that doesn't seem too clean. I think i will make a server app out of the signalr stuff and call the server for orderbook info from a separate script. This seems the cleanest solution(least cluttered "await" code) so far atleast.

**Comment by dparlevliet** [comment]
yep

**Comment by hippylover** [comment]
It just occured to me that if i make a server out of the signalr stuff then perhaps whenever i send a call to the server the server may block the stream at that point anyway. So it would seem that i have to make atleast the server async anyway. Do you know how i would do that?

**Comment by dparlevliet** [comment]
yes, you can use an async webserver like tornado or threads and IPC

**Comment by qraftec** [comment]
Hi thank you very much for your code!
Can you give one more help? 
It seems that to make orderbook,  I have to use QueryExchangeState to get snapshot of orderbook and then update data. 
But I can't figure out how to do it in python. How can i do that?

**Comment by qraftec** [comment]
https://github.com/gtklocker/bittrex-orderbook/blob/master/index.js
It uses QueryExchangeState to set initial state. Because I don't know nodejs it is hard to change it to python. Need your help!

**Comment by dparlevliet** [comment]
I submitted the python code to a python library and they have created a class you can use https://github.com/ericsomdahl/python-bittrex/issues/57

**Comment by hippylover** [comment]
Ah, cool. I've had it working for quite some time though. Thanks for the
help!

On Fri, Oct 20, 2017 at 11:28 PM, David Parlevliet <notifications@github.com

**Comment by qraftec** [comment]
@dparlevliet 
Thanks for your comment, but it seems my problem is not solved yet. 
Class you linked is same as your code, and I can't find clue to use QueryExchangeState to get initial state of orderbook

I used this code, but it doesn't working 

'''python
from requests import Session
from signalr import Connection

markets = [['BTC-ETH']]([url](`url`))

session = Session()

connection = Connection('http://socket.bittrex.com/signalr', session)

corehub = connection.register_hub('coreHub')


def print_error(error):
    print('error: ', error)

def print_raw_data(*args, **kwargs):
    print(args, kwargs)

def ticker_data(*args, **kwargs):
    print("ticker", (args, kwargs))

def market_data(*args, **kwargs):
    print(args, kwargs)


#connection.received += print_raw_data
connection.error += print_error

connection.start()
print("sending subscription request")

corehub.server.invoke('SubscribeToExchangeDeltas', markets[0])
corehub.server.invoke('QueryExchangeState', markets[0])


corehub.client.on('updateExchangeState', print_raw_data)

connection.wait(120000) # close the connection if no message is received after this many seconds
'''

**Comment by qraftec** [comment]
Thanks. I found the way!
