### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by babrums** [dparlevliet/node.bittrex.api#26]
Need to wait for response less than 20 seconds. It is possible to add timeout option?
Output sample: `requested from https://bittrex.com/api/v1.1/public/getorderbook?market=BTC-XEM&depth=20&type=both in: 57.362s
`
Sometimes it freezes for 10 minutes until I stop it. Have no idea why.

**Comment by dparlevliet** [comment]
This has been pushed in the newest version.
