### ISSUE TITLE
Error on buylimit?

### ISSUE THREAD

**Issue by gerardo15** [dparlevliet/node.bittrex.api#27]
Hello

My Node has been working fine for a few days and now im getting errors on buylimit?
console.log('Sending buy order  ' + mercado + " - " + ammount + " - " + marketbuy);
bittrex.buylimit({market: mercado, quantity: ammount, rate: marketbuy}, function (data2, err) {
          var uuid = data2.result.uuid;
});

Sending buy order  BTC-SNGLS - 1314.16837782 - 0.000051135
ERROR: TypeError: Cannot read property 'result' of null

Any ideas? i logged in and there is sufficient BTC for the trade, is the second trade i get the error.

**Comment by dparlevliet** [comment]
please check if there is an error being returned to you

```javascript
bittrex.buylimit({market: mercado, quantity: ammount, rate: marketbuy}, function (data2, err) {
if (err) {
  return console.error(err);
}
var uuid = data2.result.uuid;
});
```

**Comment by gerardo15** [comment]
Well.. my mistake..it seems it is inssuficient balance
let me close this.
