### ISSUE TITLE
Transfer repository and package ownership

### ISSUE THREAD

**Issue by joshendriks** [dparlevliet/node.bittrex.api#28]
Good job, talking over from n0mad01. Thanks for that!

Did you know you can [transfer the repository ownership](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)? It does have quite some advantages to not be just a fork. like searchable code:
![image](https://user-images.githubusercontent.com/1027541/30642556-a2cf6b76-9e0b-11e7-8c7d-e1abbb23aed4.png)

Same can be done at npmjs....

**Comment by dparlevliet** [comment]
Yes - he transferred ownership of the npm package the other day, but I'm in the middle of setting up a new house so I haven't got to that yet. However he obviously has not transferred the github, at least not yet. Not much I can do about it. If he does, that'd be ideal. 

I'm putting together another version of the package to start supporting the v2 api and ES6 and promises so I imagine people will start swapping over to that once it's done anyway.
