### ISSUE TITLE
Minimal NodeJS version

### ISSUE THREAD

**Issue by Alexsey** [dparlevliet/node.bittrex.api#32]
In `package.json` it has a target version of node as 0.10+. Are we really should support such old engine version?

**Comment by dparlevliet** [comment]
This package is old. I make the assumption that people who made their bots years ago probably haven't changed their environment so they might still be running that version. 

I have another version in development that will be making use of the v2 api features explicitly and ES6/promises. I will continue to maintain this library once that's completed but new features will not be added unless needed.

**Comment by Alexsey** [comment]
And how about just a major version bump? Nobody gets broken from backward incompatibility if it would came in 0.8 version
