### ISSUE TITLE
Timeout API requests

### ISSUE THREAD

**Issue by pditmar** [dparlevliet/node.bittrex.api#35]
Any way we can put a time-out on the API requests?

`requested from https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-NEO in: 0.865s
write point success
getmarketsummary
requested from https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-NEO in: 370.385s
write point success
getmarketsummary`

This one took quite long, is it possible to stop waiting for the request and run into a time-out?

**Comment by dparlevliet** [comment]
Are you using the newest version of the forked package?

**Comment by pditmar** [comment]
Hmmm no I don't seem to. I am running it in docker, dependencies were as follows : 

  "dependencies": {
  "express": "3.2.4",
  "influxdb-nodejs": "2.7.4",
  "node.bittrex.api": "0.6.6",
  "hoek": "4.2.0"
  } 

When I try to change them to 0.7.6 I get an error npm ERR! version not found: node.bittrex.api@0.7.6

**Comment by dparlevliet** [comment]
I see, you're using the original package instead of the forked package. The fork package is ``node-bittrex-api``

**Comment by dparlevliet** [comment]
I have pushed the latest version to the original package now that I have access, you should be able to update now. The version is 1.0.0 to indicate to people that there's been a major change.

**Comment by pditmar** [comment]
Thnx I installed the latest version!
