### ISSUE TITLE
Need more info on websockets and limit orders

### ISSUE THREAD

**Issue by sameepsi** [dparlevliet/node.bittrex.api#37]
Hi
I want to ask a question. Suppose I place a limit buy order for certain market. Now I get uuid in immediate response. But is there way to know when the order is actually executed by the bittrex or I have keep asking bittrex for such orders(data pull). This will be a very terrible idea and will impact the application performance.
Generally platforms provide either webhook facility or sockets to listen for such events.
In case of bittrex can similar thing can be achieved using sockets of pull is the last choice we are left with.
Thanks
Sameep

**Comment by dparlevliet** [comment]
You have to keep polling Bittrex for this information. The Websocket API is not officially released by Bittrex yet and as such does not support authentication using api keys so we cannot get notifications of account related events. This is expected to change but we do not know when.

**Comment by nengine** [comment]
If I want to get the market data such as orders/fills do I need to poll? Is there limit per second on polling?
