### ISSUE TITLE
How to calculate % change?

### ISSUE THREAD

**Issue by surendrakumar1992** [dparlevliet/node.bittrex.api#40]
![image](https://user-images.githubusercontent.com/12594740/31065039-def86f78-a75f-11e7-880f-e39c3397f466.png)

I am using getmarketsummary api. How to calculate % change for this market?

Thanks in advance

**Comment by dparlevliet** [comment]
You have to track that information and calculate that yourself.

**Comment by surendrakumar1992** [comment]
Hi
Can you please help me? how i can calculate from above data?

Thanks
