### ISSUE TITLE
Maintaining an order book is unclear

### ISSUE THREAD

**Issue by superqd** [dparlevliet/node.bittrex.api#43]
The entire order book for a market, say, BTC-ETH, is dozens and dozens (if not more) orders outstanding.  Yet, when subscribing via websockets, you only ever get a handful of orders in the Buys and Sells.  I'm assuming these are changes to the order book, yet it is unclear how to maintain the state of the *entire* order book for a given market.

1) What does Type mean on the returned values for the orders (there are Rate and Quantity and Type)?  What is the range of values, and what does each mean?

2) How do you build the order book and maintain it?  If I make a rest call to get the current order book, how can you correlate the data in the subscription with the order book pulled down via rest?   That is, how can you determine which orders were changed (or how the order book is changed by the new data)?

I'd like to maintain an order book for a given market, but the websocket feed appears mostly to be just anonymous deltas to the order book, with no way to correlate the websocket data with the restful data.

I'm sure I'm missing something, I just don't know what.  Is there any additional info someone could point me to?  Or is there a simple explanation for this I am lacking?

**Comment by dparlevliet** [comment]
I could explain it, but it's probably easier for you to just use this library instead https://github.com/gliwka/bittrex-market

**Comment by superqd** [comment]
Hmmm.  I appreciate the link, and the doc looked promising, but when I copied their sample code and ran it, it simply said "Connect Failed" "Connection aborted".  

I will look through their code and see if I can glean the answers to my questions there.

**Comment by superqd** [comment]
Hmmm.  So, there seem to be a call to QueryExchangeState, and using that plus the nounce values to order the changes to the order book.

However, in looking for an api doc for the websocket calls for bittrex, I cannot find any.  Is the websocket connection supported by Bittrex?  If not, do folks using your library run the risk of getting access to Bittrex cut off?

**Comment by dparlevliet** [comment]
It is supported and used by Bittrex, but it is not yet documented. They are still actively maintaining it and evolving it so they wont release a spec for it until it's complete. You have no risk to your account by using the Websockets but you do have a risk that the functionality may change without notice.

**Comment by superqd** [comment]
Thanks.
