### ISSUE TITLE
bittrex.tradesell is not a function ??

### ISSUE THREAD

**Issue by keepthefaya** [dparlevliet/node.bittrex.api#44]
I got : TypeError: bittrex.tradesell is not a function

When i try to call

var bittrex = require('node.bittrex.api');`
bittrex.tradesell({
  		MarketName: DesiredPair,
  		OrderType: 'LIMIT',
  		Quantity: amount,
  		Rate: rate,
  		TimeInEffect: 'GOOD_TIL_CANCELLED', // 'IMMEDIATE_OR_CANCEL', 'GOOD_TIL_CANCELLED', 'FILL_OR_KILL'
  		ConditionType: 'NONE', // supported options are 'NONE', 'GREATER_THAN', 'LESS_THAN'
  		Target: 0, // used in conjunction with ConditionType
	}, function( data, err ) {
  		console.log( data );
	});`

getbalances work fine, i dont understand

**Comment by dparlevliet** [comment]
What version do you have installed?

**Comment by keepthefaya** [comment]
ok, my bad i have with : var Nodebittrexapi = require('node-bittrex-api'); instead of var Nodebittrexapi = require('node.bittrex.api');

i got null during my order but error fixed
