### ISSUE TITLE
Dose this lib support cross origin?

### ISSUE THREAD

**Issue by alicePan** [dparlevliet/node.bittrex.api#45]
I use the following code
`  
  const bittrex = require('node-bittrex-api')

  bittrex.websockets.client(function (client) {
    var websocketsclient = client
    websocketsclient.serviceHandlers.messageReceived = function (message) {
      console.log(message)
    }
    websocketsclient.serviceHandlers.onerror = function (error) {
      console.log('some error occurred', error)
    }
  })`

in my frontend pages and open it in `http://localhost:8080/#/`
The browser tells me that 

> Failed to load https://bittrex.com/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
node.bittrex.api.js?f5f0:164 Cloudscraper error occurred
(anonymous) @ node.bittrex.api.js?f5f0:164
node.bittrex.api.js?f5f0:165 Object

**Comment by dparlevliet** [comment]
This lib isn't intended to work in the browser - yet - but i do believe some other people have had success using it via browserify

**Comment by hannut91** [comment]
I did using browserify but had failed 
 
I received the error message
"Failed to load https://bittrex.com/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
