### ISSUE TITLE
Websocket disconnect

### ISSUE THREAD

**Issue by khuezy** [dparlevliet/node.bittrex.api#47]
Hi, I know that there's been 2-3 previous issues with the websocket disconnecting and never retrying.

I'm still experiencing that every 2-3 hours even after trying all the suggestions.

How did you solve it?

Thanks!

**Comment by dparlevliet** [comment]
I don't think there has been a resolution yet - it's an issue that I'm not able to replicate and everyone that has had the issue never said if they solved the issue or not. If I were in your shoes I'd be trying to figure out a way to tell if the socket has disconnected without the event firing by looking at the connection variables and seeing what's available and/or trying to send periodic events and seeing if you get errors.

Let me know how you go, I'd appreciate it.
