### ISSUE TITLE
Creating multiple websockets

### ISSUE THREAD

**Issue by keu** [dparlevliet/node.bittrex.api#48]
Hello!

I am looking for a way to create separated readers for 'market' and 'global' queue. As far as I understand node.bittrex.api use single wsclient.
Is there any reason to choose such design over creating multiple clients?

Thanks

**Comment by dparlevliet** [comment]
Hey bud,

Why you would need multiple socket connections? I have a bot listening to global and to every market pair that Bittrex has and I've never encountered an issue that made me think I need a separate socket connection.
