### ISSUE TITLE
Data Timestamps timezone?

### ISSUE THREAD

**Issue by bernatfortet** [dparlevliet/node.bittrex.api#5]
Does anybody know what's the timezone for TimeStamps? 
This is the format: `2017-09-10T23:36:00`
I see a discrepancy between this timestamp and what I can see in their website's graphs. I guess it's because those graphs adapt to my timezone, but the data comes from the server.

**Comment by dparlevliet** [comment]
I believe they're UTC

**Comment by smhty** [comment]
Yes, It is UTC
