### ISSUE TITLE
It's there a way to get the BTC- USD Price that Bittrex uses?

### ISSUE THREAD

**Issue by gerardo15** [dparlevliet/node.bittrex.api#53]
On the website you can see.

1 BTC = $7444.2963

is it posible to get that value from the api?

**Comment by dparlevliet** [comment]
The Bittrex website uses the API call ``https://bittrex.com/Api/v2.0/pub/currencies/GetBTCPrice`` -- we don't currently have this as a standalone function but we can add it.

**Comment by gerardo15** [comment]
Nice.

How did you find it? I cannot find the API V2 documentation anywhere

**Comment by dparlevliet** [comment]
Correct, there's no documentation because it's not yet officially release - I've been using the Chrome developer tools.

**Comment by nguyenhmp** [comment]
hey dparlevliet,
This is old but was wondering if you could guide me on how you figured out the endpoints of the api. Thought I would try and ask! Thanks ahead for the library!

**Comment by rubenbryon** [comment]
In chrome->inspect (on bittrex.com ofc), go to network tab, reload page (filter on XHR and fetch) and you'll see it right there.
