### ISSUE TITLE
Is it possible to use Websockets with private API?

### ISSUE THREAD

**Issue by hexdump2002** [dparlevliet/node.bittrex.api#54]
I have been taking a look at the lib and did not find any way to authenticate through websockets for example to call QueryBalanceState. Is this possible at the current state of the lib?

Thanks in advance.

**Comment by dparlevliet** [comment]
It's not possible at this stage. Bittrex does not have a method for authenticating with your api keys.

**Comment by hexdump2002** [comment]
Ok, thanks for the fast answer.
