### ISSUE TITLE
buylimit returns null

### ISSUE THREAD

**Issue by sacredwx** [dparlevliet/node.bittrex.api#58]
Hi guys, I'm trying to make a standard buy trade and getting null in response.
getbalances and getticker calls work great.
API permissions all enabled.
Tried also v2 tradebuy with the same result.

Thanks in advance.

`
const bittrex = require('node.bittrex.api');

bittrex.buylimit({
	market : 'BTC-LTC',
	quantity: 1.2,
	rate: 1.3
}, (data) => {
console.log(data); // Output: null
});
`

**Comment by Nilotaviano** [comment]
Have you checked the second parameter for an error?
```
const bittrex = require('node.bittrex.api');

bittrex.buylimit({
market : 'BTC-LTC',
quantity: 1.2,
rate: 1.3
}, (data, error) => {
    if(!error)
        console.log(data);
    else
        console.log(error);
});
```

**Comment by sacredwx** [comment]
You are right, I went out lame))
I just thought, that the first parameter might be anything, but null anyway.
Sorry for this.

**Comment by Nilotaviano** [comment]
No problem. Can you close the issue?

**Comment by sacredwx** [comment]
Sorry, couldn't find the button.
