### ISSUE TITLE
npmjs publish?

### ISSUE THREAD

**Issue by d0whc3r** [dparlevliet/node.bittrex.api#6]
Could this package be submitted to npmjs?

**Comment by dparlevliet** [comment]
Not under this name - I would have to rename it which isn't ideal. I'm giving the original author some time to make me a collaborator. It's only been a day, I'll decide tomorrow.

**Comment by TamerCC** [comment]
Until this is resolved maybe take the line 
`npm install node.bittrex.api`
out of the read.me

**Comment by dparlevliet** [comment]
The npm package is available now. Please see the ``Quick start`` section of the README.md.
