### ISSUE TITLE
How can get all order history

### ISSUE THREAD

**Issue by vanhung89** [dparlevliet/node.bittrex.api#60]
I used `bittrex.getorderhistory('', function(data1, err ) { // do somethings }); `to get order history. But it just return 9 records. How can I fetch all order history?

**Comment by dotsoftware** [comment]
I just tested it and received exactly 100 trades from getorderhistory. I call the function with brackets if I don't want to limit it to certain markets, like this: getorderhistory( **{}**, function(data,err) ....
Afaik, all history is only supported on the website as CSV download

**Comment by lukehaines2** [comment]
You can just use a custom request, like below. Worked for me. But bear in mind I believe Bittrex only sends 1 month's worth of orders at the moment, otherwise you have to download a CSV from the actual site as @dotsoftware suggested.
```const url = 'https://bittrex.com/api/v1.1/account/getorderhistory';
bittrex.sendCustomRequest( url, function( data, err ) {
  if (err) return console.log( err);
  console.log( data );
}, true);```
