### ISSUE TITLE
Websocket listen for updateSummaryState does not work

### ISSUE THREAD

**Issue by remss** [dparlevliet/node.bittrex.api#68]
Hello,

The `example/bittrex.websockets.listen.example.js` does not work. in 0.7.6
The data argument in the listen callback is always `{ unhandled_data: {} }`

I rolled back to previous versions, or try the last master and the bug still here.
Maybe something changed in the Bittrex WS protocol ?

Thanks

**Comment by franciskim722** [comment]
Please refer to https://github.com/dparlevliet/node.bittrex.api/issues/67

**Comment by Ddzhenyik** [comment]
Hi! In my case I can reveive only 2 types of messages: "unhandled_data" and "updateExchangeState".. but "updateSummaryState" is missed.

**Comment by aloysius-pgast** [comment]
@Ddzhenyik : Can you try something similar to https://github.com/dparlevliet/node.bittrex.api/issues/67#issuecomment-346277723 ? It worked for me

**Comment by Ddzhenyik** [comment]
@aloysius-pgast Thanks a lot! At the moment it works perfectly!
