### ISSUE TITLE
I cannot get any result from API call

### ISSUE THREAD

**Issue by denigada** [dparlevliet/node.bittrex.api#71]
Hello. I am trying out the bitter API and learning javascript. So I have an index.html file and a main.js file. I included the js file in the HTML, however, this doesn't produce any output. Can anybody see why this doesn't work?

![screen shot 2017-11-25 at 10 43 29 pm](https://user-images.githubusercontent.com/5206952/33236949-2671341e-d232-11e7-9360-1f2ceae99ef5.png)

**Comment by andrewedera** [comment]
Can you post the error in your console log? I'm assuming you are using it on front-end since you mention index.html, etc. this API Wrapper is meant for node.js(server-side) and not on frontend. however you can still use some fetch API (non-websocket) on frontend using requirejs or browserify.

**Comment by denigada** [comment]
It is not even printing any errors. Thank you for letting me know that, I didn't know node.js is for only frontend. So how can I use this API on my frontend ? Will it be slow because of the things I need to do to make it work on frontend ? Thank you so much

**Comment by andrewedera** [comment]
Create **app.js**
```
var bittrex =  require('node-bittrex-api');

bittrex.getmarkethistory({ market : 'BTC-LTC' }, function( data, err ) {
	document.getElementById("messages").innerHTML = JSON.stringify(data);
});
```

Create **index.html**
```
<!doctype html>
  <body>
    <ul id="messages"></ul>
    <script src="output.js"></script> 
  </body>
</html>
```

install **browserify** more info at http://browserify.org/

in command line type **_browserify app.js -o output.js_**

**Comment by denigada** [comment]
I get this error: Error: Cannot find module 'node.bittrex.api/node.bittrex.api'

I am sure the file is there, what do you think might be the issue?

**Comment by denigada** [comment]
I did it but i it outputting a strange result full of codes in the output.js file. And how can I see the change on the list? I open the index.hmtl in safari but it is not changed when I run this. Can you please help me ? I am a beginner

**Comment by dparlevliet** [comment]
Sorry, I do not recommend nor is it intended for this library to client-side.

**Comment by denigada** [comment]
What is wrong with using this on client side?
