### ISSUE TITLE
how to use the API functions in a function

### ISSUE THREAD

**Issue by denigada** [dparlevliet/node.bittrex.api#73]
I'm trying to get the BTC balance but this does not seem to work. Can someone help? It gets undefined.

![screen shot 2017-11-28 at 4 55 44 pm](https://user-images.githubusercontent.com/5206952/33346341-60a43302-d45d-11e7-9121-2a477f1918bd.png)

**Comment by dparlevliet** [comment]
you need to wrap it in a promise
