### ISSUE TITLE
Websocket disconnection after some hours

### ISSUE THREAD

**Issue by maltium** [dparlevliet/node.bittrex.api#75]
After a few hours, some times even just an hour, I get disconnected from the websocket. Since it takes a while to resubscribe to the individual tickers, I would like to avoid disconnections.

Can I do something to prevent this?

**Comment by dparlevliet** [comment]
Nope. This is a known issue with a) websockets in general and b) Bittrex - but to be fair it happens with every exchange. Sorry, reconnections are the only solution.
