### ISSUE TITLE
Error with Asynchronous requests - Async await

### ISSUE THREAD

**Issue by leoplct** [dparlevliet/node.bittrex.api#76]
I'm having problem with async function, and it seems already resolved in the older version of node.bittrex.api library.
https://github.com/n0mad01/node.bittrex.api/issues/49

```
const res = await bittrex.tradebuy(params, function( data, err ) {

    		   if(err){
				        console.error(err)
				        return err
  			   }else{
  				      console.log( data );
  					   return data;
  			   }
    		});
        resolve(res);
```

SyntaxError: Unexpected identifier on bittrex

**Comment by aurbina83** [comment]
Why are you using await with a callback? 

From what I understand, this library doesn't use promises. Async/await are for promises.
