### ISSUE TITLE
Improvement request: Cannot promisify easily as standard node convention not supported

### ISSUE THREAD

**Issue by rvenugopal** [dparlevliet/node.bittrex.api#77]
I would like to use 
```const bittrex = blueBird.promisifyAll(require('node.bittrex.api'));```
However, as the library does not follow standard node convention, I am not able to.  

> The target methods are assumed to conform to node.js callback convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.  http://bluebirdjs.com/docs/api/promise.promisifyall.html#promisification

 A work around I am using to promisify individual methods on ad-hoc basis using the below method but is not ideal (i am using 

```
function wrapWithPromise(fn) {
  return function(...args) {
    return new Promise( (resolve, reject) => fn(resolve, reject, ...args) );
  }
}

const getmarketsummaries = wrapWithPromise(bittrex.getmarketsummaries)
```

**Comment by rvenugopal** [comment]
For anyone else who might be interested, here is a function which can help promisify this library.

```
function promisifyAll(input) {
  function promisifier(method) {
    return function promisified(...args) {
      return new Promise((resolve) => {
        args.push(resolve);
        const self = this;
        method.apply(self, args); 
      });
    };
  }


  function promisifyAll(obj) {
    for (const key in obj) {
      if (typeof obj[key] === 'function' && key.indexOf('Async') === -1) {
        obj[key + 'Async'] = promisifier(obj[key])
      }
    }
  }

  promisifyAll(input);
  return input
}

const bittrexPromisified = promisifyAll(require('node.bittrex.api'));
```

**Comment by dparlevliet** [comment]
There is an option for this already. See ``inverse_callback_arguments``
