### ISSUE TITLE
Websockets listen not working

### ISSUE THREAD

**Issue by gmenti** [dparlevliet/node.bittrex.api#79]
Always returns unhandled_data.

**Comment by agarwalyeshu** [comment]
The same problem I was facing, download the latest code of this repo. Then it will work.

**Comment by gmenti** [comment]
Not working, i'm using npm version.

{ unhandled_data: {} }

**Comment by glebreutov** [comment]
I can confirm this. both 0.8.1 and 0.7.8 returns the same error.

**Comment by gmenti** [comment]
Nice!, working here with solution of glebreutov, however, some admin update the version of npm with this fix. Thankss!

**Comment by dparlevliet** [comment]
the correct package is in the README.md
