### ISSUE TITLE
Documentation of the fields retrieved

### ISSUE THREAD

**Issue by amlwwalker** [dparlevliet/node.bittrex.api#80]
Hi,
Looking at the data that comes back from the `.websockets.subscribe` endpoint, I can see:

```
  Nounce: 53229,
  Buys:
   [ { Type: 1, Rate: 0.0036498, Quantity: 0 },
     { Type: 0, Rate: 0.00364223, Quantity: 96.09497478 },
     { Type: 2, Rate: 0.00325, Quantity: 2623.09164641 },
     { Type: 2, Rate: 0.00193, Quantity: 4.87063839 },
     { Type: 2, Rate: 0.00048, Quantity: 10.56814045 } ],
  Sells:
   [ { Type: 0, Rate: 0.00369978, Quantity: 1.69001102 },
     { Type: 1, Rate: 0.0046079, Quantity: 0 } ],
  Fills: [] }
```
Looking at bittrex's api, it looks like `Type` corresponds to full/limit trade etc. however I can't find anywhere that explains how `Type` 0/1/2 corresponds to any of these trade types. 

Any help greatly appreciated

**EDIT**
I came across an answer that outlined the meaning of the states: 

> Type 0 – you need to add this entry into your orderbook. There were no orders at matching price before.
> 
> Type 1 – you need to delete this entry from your orderbook. This entry no longer exists (no orders at matching price)
> 
> Type 2 – you need to edit this entry. There are different number of orders at this price.

and in doing so, and reading around more, I understand I need to get a snapshot of the order book, and then use the socket to update my version of it. OK, that makes sense. If anyone knows the answer, is Type 2 (above) the new number of orders, or an amount to add/subtract from the amount in your synced order book?

**Comment by dparlevliet** [comment]
It's the new total quantity for that price so if you want to know the difference you would need to compare the value you currently have stored to the new value.
