### ISSUE TITLE
How to "unsubscribe" or Subscribe to other markets?

### ISSUE THREAD

**Issue by CryptoTropico** [dparlevliet/node.bittrex.api#83]
Hello, 

I am using this:

function updateMarket(dataM) {
		bittrex.websockets.client(function() {
		  console.log('Websocket connected');
		  bittrex.websockets.subscribe([dataM], function(data) {
			if (data.M === 'updateExchangeState') {
			  data.A.forEach(function(data_for) {
				console.log('Market Update for '+ data_for.MarketName+" Price: "+data_for.Fills[0].Rate);
				client.emit('marketUpdate', data_for.Fills[0].Rate);
			  });
			}
		  });
		});
	};

Is there a way to unsubscribe and stop receiving updates, and then subscribe to other markets???

**Comment by aloysius-pgast** [comment]
From my experience, the only way to cancel a subscription is to reconnect (there is no SignalR method to cancel an existing subscription)

**Comment by dparlevliet** [comment]
@aloysius-pgast  is correct, right now that's the only way.

**Comment by dalaverd** [comment]
How do we reconnect properly without keeping the precedent existing subscription alive?
