### ISSUE TITLE
getNonce : use while instead of calling itself when nonce is used

### ISSUE THREAD

**Issue by peterkaptein** [dparlevliet/node.bittrex.api#85]
Because there is no wait inside of the "if / getNonce" the current implementation will just hit the maximum stack of nested calls and bomb out
  
Suggestion: use something like 

   var nonce = new Date().getTime(); 

   while(lastNonces.indexOf(nonce)>-1){
      nonce = new Date().getTime(); // Repetition of the above. This can probably done better :-)
    }

    
Instead of:

    if (lastNonces.indexOf(nonce) > -1) {
      // There is no wait here, so during the same millisecond, we will call ourselves many times
      return getNonce();
    }

**Comment by onfqzmpgvr** [comment]
I encountered this bug, thank you very much @@
So finally, it will be like this right?

```
  var getNonce = function() {
    var nonce = new Date().getTime();

    while(lastNonces.indexOf(nonce)>-1){
      nonce = new Date().getTime(); // Repetition of the above. This can probably done better :-)
      }

    // keep the last X to try ensure we don't have collisions even if the clock is adjusted
    lastNonces = lastNonces.slice(-50);

    lastNonces.push(nonce);

    return nonce;
  };
```

**Comment by peterkaptein** [comment]
Yes
