### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by dotsoftware** [dparlevliet/node.bittrex.api#86]
Is it possible to modify the plugin so that it can create an array of bittrex instances? 
Momentarily, only one user can use the application at the same time.

**Comment by springjben** [comment]
I am also wondering this. This is very important!

**Comment by dparlevliet** [comment]
There are native work arounds such as webworkers. With the way this library was originally written it's currently not possible. I do want to try do this, but I have to think about the people who don't need it, too. Unnecessarily breaking someones bot is always out of the question for me so I need to implement it in a way that is backward compatible. I'm really busy for a few more weeks then I will have a lot more free time.

**Comment by springjben** [comment]
Another contributed helped me implement this! Its done in a very clever yet simple way.

**Comment by SagiMedina** [comment]
@springjben Please share it with us :)

**Comment by aloysius-pgast** [comment]
@SagiMedina : I think @springjben is referring to https://github.com/dparlevliet/node.bittrex.api/pull/66

**Comment by pldin601** [comment]
I created #66. You could check it before changes will be accepted. Just refer to npm documentation how to install package from git:

```shell
npm i git+https://github.com/pldin601/node.bittrex.api.git
```

**Comment by dparlevliet** [comment]
This is in the newest release
