### ISSUE TITLE
Race condition assigning wsclient variable when calling both .listen and .subscribe

### ISSUE THREAD

**Issue by TheRealest** [dparlevliet/node.bittrex.api#87]
Now that `.subscribe` does not also subscribe you to the `updateSummaryState` messages, I'm having to call both `.listen` and `.subscribe` (I imagine many people who use both message types call these methods one after the other). Unfortunately, since you can't pass a callback into these methods that is called after they are done, only a message handler, there's no way to let one finish establishing the WS client before calling the other one. This results in `connectws` being called twice and two separate WS client connections being created. I'm not sure how this is handled by bittrex, but I noticed this because sometimes when starting up my script the nonces get screwed up right from the start (I get updates with overlapping info with two parallel series of nonces), plus the two "connected" messages.

There is a workaround you can use right now: the `.client` method. Because the callback argument for this function is a true callback, rather than setting a message handler, it will be called after the WS client is created and the connection is established, so `wsclient` will be set and calling the other methods will skip the body of `connectws`. Here's the code I used (it's coffeescript but you get the idea):

```
bittrex.options @options
bittrex.websockets.client (client) =>
  # these methods are called inside the `.client` callback to avoid a race
  # condition where both `.listen` and `.subscribe` try to create separate
  # WS client connections -- inside this callback we know `.client` will
  # have already created the connection
  bittrex.websockets.listen()
  bittrex.websockets.subscribe @markets, @websocketsSubscribeHandler
```

A non-breaking change that could be made to address this would be to add a callback argument to the function signature of the two methods in question, like this:
```
listen: function(messageHandler, callback)
subscribe: function(markets, messageHandler, callback)
```
This would be non-breaking but still allow people to use callbacks for when these methods complete (they are async functions after all). The WS client could be passed through to the callbacks as well to kind of follow the pattern of `.client`.

**Comment by dparlevliet** [comment]
``listen()`` and ``subscribe()`` should be called in the ``client()`` or ``onConnect()`` callbacks - the establishment of connections for these functions was only retained for backward compatibility. I recommend using the ``onConnect()`` method so you can resubscribe/listen if a disconnect occurs. Given that, I don't see the need to add another callback, because ``onConnect()`` does what you want already. Open to hearing a case for why it doesn't and why you would need the old method instead.

**Comment by TheRealest** [comment]
Great point, that makes sense. I see now in the first websockets example in the readme that that's how it's shown. We might make this fact a bit more obvious in the readme sections on `websockets.listen` and `websockets.subscribe` (here: https://github.com/dparlevliet/node.bittrex.api#websocketslisten).

Quick question regarding your suggestion about using the `onConnect` handler: if there's a disconnect/reconnect will nothing come through if those subscribe commands aren't sent again? I haven't done enough testing around reconnecting to know how it all works, but I'm wary of double subscribing or something like that.
