### ISSUE TITLE
listen() not working again

### ISSUE THREAD

**Issue by kyletan7** [dparlevliet/node.bittrex.api#88]
Using 0.8.1, but I'm receiving empty data from Bittrex again. The fix here still seems to work fine though: https://github.com/dparlevliet/node.bittrex.api/issues/67#issuecomment-346277723

**Comment by leberknecht** [comment]
Uh, thanks for the tip with the workaround! 
Can confirm, i'm also getting empty data object (since a while actually, i think ~2 months?)

**Comment by thechile** [comment]
thanks.. #67 worked for me.. phew.

**Comment by dparlevliet** [comment]
I cannot replicate this. It works fine for me in the latest version.
