### ISSUE TITLE
WS: Difference between listen and subscribe

### ISSUE THREAD

**Issue by bernatfortet** [dparlevliet/node.bittrex.api#9]
What's the difference between:

`bittrex.websockets.listen`
and 
`websockets.subscribe`

**Comment by dparlevliet** [comment]
Listen subscribes to just the global data such as ticker updates. Subscribe attaches to both the global and the specified market data. I'll make note of this in the documentation.

**Comment by gerardo15** [comment]
I was thinking about it today.. i was about to ask in here but i thought that it was something too obvious, but could not find anything on the internet.
