### ISSUE TITLE
What is the Sell Type 0 or 1? Why Quantity 0?

### ISSUE THREAD

**Issue by stefek99** [dparlevliet/node.bittrex.api#95]
Just figuring out how to interpret the data...

```
Market Update for BTC-ETH { MarketName: 'BTC-ETH',
  Nounce: 299553,
  Buys: [],
  Sells:
   [ { Type: 1, Rate: 0.0456203, Quantity: 0 },
     { Type: 0, Rate: 0.04579994, Quantity: 0.1600311 } ],
  Fills:
   [ { OrderType: 'BUY',
       Rate: 0.0456203,
       Quantity: 0.9866154,
       TimeStamp: '2017-12-19T16:29:29.577' } ] }
```

**Comment by ZhiweiWang** [comment]
The market update only show diff with last order book for reduce network usage. So Quantity:0 means this Rate:0.0456203 was just removed from order book. And Quantity:0.1600311 means the quantity of Rate:0.04579994 was modified to 0.1600311. You don't have to check what is the type.

**Comment by aloysius-pgast** [comment]
More info in https://github.com/dparlevliet/node.bittrex.api/issues/80
