### ISSUE TITLE
Socket.io for websockets?

### ISSUE THREAD

**Issue by springjben** [dparlevliet/node.bittrex.api#96]
> bittrex.websockets.listen(function(data, client) {
>  if (data.M === 'updateSummaryState') {
>    data.A.forEach(function(data_for) {
>      data_for.Deltas.forEach(function(marketsDelta) {
>        console.log('Ticker Update for '+ marketsDelta.MarketName, marketsDelta);
>      });
>    });
>  }
> });

How would I write that in a sockets.io syntax? io.listen()..

Or is it not possible as its written using all the normal websockets stuff? I have only ever used socket.io is all.

Thank you!

**Comment by springjben** [comment]
That might sound stupid as I can just use the websockets you use and output it using sockets.io

**Comment by springjben** [comment]
As I am doing this atm:

`io.on('connection', function(client) {
    console.log('Client connected...')
    bittrex.websockets.client(function() {
      console.log('Websocket connected');
      bittrex.websockets.subscribe(['BTC-ETH'], function(data) {
        if (data.M === 'updateExchangeState') {
          data.A.forEach(function(data_for) {
            console.log('Market Update for '+ data_for.MarketName, data_for);
          });
        }
      });
    });`

**Comment by springjben** [comment]
https://i.gyazo.com/08c191d8f24fa1567f7ab6c2b1b48b48.png

**Comment by springjben** [comment]
Also it takes ages to connect. Once it has been connected its fine. Just getting connectd.

**Comment by dparlevliet** [comment]
Socket.io is its own websocket protocol. Bittrex uses SignalR. You don't need to worry about how the sockets work, this package handles that for you, you just have to connect then subscribe or listen.
